export const narrativeTriggersToText = {
    gameStart:'You find yourself in a backwater mining settlement. The husks of abandoned buildings loom over rusting excavators and long dead robots. Inside one of these structures you find a grimy but still usable ore refiner. You also find an automaton fabricator. It\'s primitive by modern galactic standards, with some steel you could probably create a simple mining robot. At the edge of town an open pit descends into the mines. You ready your pickaxe.',
    hasMined: 'You find that the old mine still has plenty of ore remaining. You successfully extract some.',
    hasUnlockedPickaxeUpgrade1: 'After numerous subterranean hours, the rhythm of your pickaxe swings begin to feel natural. You believe your current tool is your only obstacle to further riches. (You can now wield the next tier of pickaxes).',
    hasUnlockedGoldMining: 'There\'s much more to mining than you initially thought. As you familiarize yourself with the rock and soil, you discover that you can sometimes find specks of gold. (You\'ve unlocked the ability to occasionally find gold when mining. This chance scales with your level and does not apply to your automatons.)',
    hasRefinedOre: 'The machine\'s internal furnace roars and groans. From its molten innards emerges a single steel ingot.',
    hasBuiltAutoMiner: 'Like an off-world Prometheus, you have birthed life. Well, not "life" per se, and all you did was follow the manual, but you did manage to get a rather sad looking robot to emerge from the fabricator. It slowly shuffles off to the mines.',
    hasBuiltAutoRefiner: 'You fumble a bit, but eventually you get the fabricator to output a working robotic refining assistant. It dutifully takes its place next to the ore refiners and begins to work.',
    hasUnlockedAutoRefiner: 'You\'ve fabricated enough robots that you feel comfortable moving on to the "advanced" section of the manual. A section entitled "Automated Refining for Absolute Dumb-Dumbs" seems up your alley. (You can now build auto refiners)',
    hasMinedGold: 'Eureka! You\'ve found a nugget of gold within the ground.',
    hasUnlockedShop: 'A rusted and beaten shuttle descends from the skies. Its landing gear creaks as it settles into the center of town. An alien - presumably drawn by the smoke of your refineries- emerges and wearily looks around. It\'s wearing a leather duster and ten gallon hat, both of which look comically oversized on the lithe species which you don\'t recognize. The alien throws up a door on its ship to reveal an array of mining equipment. After some crude pantomiming you manage to get a price estimate for the gear. ',
    hasUpgradedPickaxe: 'The alien hands you the tool in exchange for your gold. It immediately feels like an improvement over your previous pickaxe. With your skills, you feel that you\'ll be able to mine far more efficiently. (You have increased the amount of ore that you get from each swing. Future pickaxe upgrades will increase this bonus further.)',
    hasUnlockedAutoGoldMiner: 'TODO, has unlocked auto gold miner, something to the effect of ',
    hasBuiltAutoGoldMiner: 'TODO hasBuiltAutoGoldMiner need to mention that it is slow ',
    hasBuiltAdvancedAutoMiner: 'TODO (Something about far sleeker, maybe even approaching graceful. It will mine five ore at a time)',
    tradingUnlock1: 'You have done a fair deal of buying and selling. Your haggling skills now allow you to sell resources at a better rate. (Leveling trading further will increase this bonus)',
    hasBuiltNeuronUplink: 'TODO, something about feeling a tad uncomfortable about installing a jury rigged computer in your head but you\'ve done worse. (You\'ll now passively gain a trickle of experience in the selected skill)',
    hasUpgradedNeuronUplink: 'TODO, with this new firmware update, you can learn even faster without having to get up. (You gain passive experience at an improved rate)',
    hasBoughtShip: 'TODO, To call this ship fixer-upper would be an understatement, but this small craft will eventually be able to take you across the planet\'s surface.',
    hasRepairedThrusters: 'TODO. You\'ve fixed all four thrusters of your craft. Now it can actually move.',
    hasRepairedLandingGear: 'TODO, The landing gear has been fixed. Your chance of dying in a fiery crash is now slightly below 100%. Whoopee.',
    hasRepairedHull: 'TODO. Your ship no longer has gaping holes through its structure. It\'s a shame, you\'ll miss the breeze.',
    hasRepairedCockpit: 'TODO. You\' reattached the joy stick and replaced the missing switches and dials. Technically, you can  pilot your ship now. Whether you should is a whole different matter.',
    hasRepairedWings: 'TODO, repaired wings',
    hasFullyRepairedShip: 'TODO, You fully fixed your ship and can now use it to travel! It\'s slightly safer and more comfortable than being launched to your destination out of cannon.',
    hasPurchasedProspectingTool: 'TODO It\'s not pseudoscientific malarkey, it\'s got "quantum" in the name! This "totally legitimate" device will allow you to find new resources beneath the ground.',
    manufacturingUnlockTest: 'TODO manufacturingUnlockTest , not even sure if this is the level I want',
    discoveredOil: 'TODO, You can now extract oil. Say something witty. You already found gold-gold, why not black gold?',
    discoveredPlastic: 'TODO, discoveredPlastic express bewilderment at plastic nuggets',
    discoveredSilicon: 'TODO, discoveredSilicon',
    nothingFoundWhenProspecting: 'TODO,(mention that increasing your prospecting skill will improve these odds)',
    minedOutGoldVein: 'TODO, all good things must come to an end. There is no more gold in this vein.',
    discoveredGoldVein: 'TODO. You have discovered a gold vein (amount will increase with prospecting level)'
}
